### ISSUE TITLE
404 at https://feedsin.space/feed

### ISSUE THREAD

**Issue by llimllib** [muffinista/rust-rss-to-fedi#14]
Steps to reproduce:

1. message `admin@feedsin.space`
2. click login link, arrive at https://feedsin.space/?page=1
3. feed url `https://notes.billmill.org/atom.xml` and requested username `notes_billmill_org`
4. get a 404 error at https://feedsin.space/feed

Below is the request the app makes, via "copy as curl" from the web inspector:

```
curl 'https://feedsin.space/feed' \
-X 'POST' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
-H 'Sec-Fetch-Site: same-origin' \
-H 'Accept-Language: en-US,en;q=0.9' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Sec-Fetch-Mode: navigate' \
-H 'Host: feedsin.space' \
-H 'Origin: https://feedsin.space' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15' \
-H 'Referer: https://feedsin.space/?page=1' \
-H 'Content-Length: 71' \
-H 'Connection: keep-alive' \
-H 'Sec-Fetch-Dest: document' \
-H 'Cookie: access_token=<elided>' \
--data 'url=https%3A%2F%2Fnotes.billmill.org%2Fatom.xml&name=notes_billmill_org'
```

**Comment by muffinista** [comment]
Thanks for reporting this @llimllib! Do you happen to know if you got logged out as part of this? I've noticed that happening once or twice. Another possibility is that there was a random network issue of some sort. It appears that the feed is fine, so if you retry this, I think it will work.

**Comment by llimllib** [comment]
worked this time. Gremlins 🤷‍♂️

thanks!
