### ISSUE TITLE
Edit feed URL

### ISSUE THREAD

**Issue by morganfletcher** [muffinista/rust-rss-to-fedi#19]
Sorry to bother; is it possible to change the RSS URL? The one I started with is for [every change](https://www.wooljersey.com/api.php?hidebots=1&urlversion=1&days=30&limit=50&action=feedrecentchanges&feedformat=atom). I'd change it to be [new pages](https://www.wooljersey.com/index.php?title=Special:NewPages&feed=atom&hideredirs=1&limit=50&offset=&namespace=0&username=&tagfilter=&size-mode=max&size=0) only.

(I sent this via email, then realized it would be better asked in an issue.)

**Comment by muffinista** [comment]
At the moment you can't, and it's possible I'll never add the ability to change the feed url, but you can always delete the feed and recreate it.

**Comment by joosep-georg** [comment]
I can confirm that it is possible to delete a feed and (even days later) recreate it with same fediverse address and already subscribed accounts (at least on Mastodon) will continue receiving new feed items as posts.

**Comment by morganfletcher** [comment]
Seconded, I did as @joosep-georg described and was able to effectively recreate the feed.

**Comment by muffinista** [comment]
Hi, I came to the conclusion that I was overthinking some of the ramifications of allowing the feed URL to be edited, so I went ahead and implemented this, you should be able to update the URL now.
