### ISSUE TITLE
Public posts are Unlisted

### ISSUE THREAD

**Issue by joosep-georg** [muffinista/rust-rss-to-fedi#25]
In feed settings – Status Publicity: Public

But posts are still appearing in Mastodon as unlisted (open padlock).

(As a result also posts' hashtags are not indexed and can not be used to discover them.)

**Comment by muffinista** [comment]
@joosep-georg Could you point out a specific feed with this issue? Thanks!

**Comment by joosep-georg** [comment]
https://feedsin.space/feed/news.err.ee
https://feedsin.space/feed/rus.err.ee

**Comment by muffinista** [comment]
@joosep-georg thanks very much for pointing this out. Hopefully it's fixed now but let me know if it isn't.

**Comment by joosep-georg** [comment]
New posts appear as public now on Mastodon and their hashtag is also usable.

I suppose it takes a little while until status changes of existing posts will federate?

**Comment by muffinista** [comment]
Unfortunately, existing posts won't refederate, so only new ones will have the proper status.

**Comment by joosep-georg** [comment]
Oh, now I see... Thought it is possible to change the visibility of previous posts on Mastodon but seems like it is not.
