### ISSUE TITLE
Feature proposal: Apply language information to all entries

### ISSUE THREAD

**Issue by joosep-georg** [muffinista/rust-rss-to-fedi#26]
Mastodon instance I am using can offer translation when language information about post is available.

Currently it has no clue in which language the entries are and offer to translate them does not appear.

**Comment by muffinista** [comment]
I like this idea very much, it might take a little time to implement though. But it's on the list!

**Comment by joosep-georg** [comment]
Not sure, whether You have added something but "Translate" option has appeared to feedsin.space posts on Mastodon.

**Comment by muffinista** [comment]
Interesting! I haven't changed a thing.

**Comment by joosep-georg** [comment]
Great, thanks! :)

Now I discovered that the feeds I am using have incorrect language information in them ;)
