### ISSUE TITLE
Couldn't find a valid feed at that URL

### ISSUE THREAD

**Issue by Mosesofmason** [muffinista/rust-rss-to-fedi#29]
I am trying to add [a KBS News RSS feed](https://world.kbs.co.kr/rss/rss_news.htm?lang=c) to feedsin.space, which is the largest media company in Korea. However, feedsin.space is showing that the feed is invalid. I am aware that the feed doesn't fully comply with the standard, but it can still be parsed by other RSS readers. Is it possible to enhance the compatibility to allow adding this feed?

**Comment by joosep-georg** [comment]
I tried a workaround and ran the feed through https://rss.app – the result is valid: https://feedsin.space/feed/world.kbs.co.kr

**Comment by muffinista** [comment]
The feed is [definitely invalid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fworld.kbs.co.kr%2Frss%2Frss_news.htm%3Flang%3Dc), even if other parsers are managing to handle it. I would like to accept as many feeds as possible, but I don't have the time or resources to really do that, and it's the sort of thing that would be likely to cause a lot of other problems down the line.

**Comment by joosep-georg** [comment]
I agree with @muffinista, the correct way of fixing this is to inform KBS and ask them to fix the feed.

**Comment by joosep-georg** [comment]
> 
I am not planning to pay for it.
