### ISSUE TITLE
Display feed Name/Title in profile instead of Fediverse name/address  

### ISSUE THREAD

**Issue by joosep-georg** [muffinista/rust-rss-to-fedi#33]
Currently feed name is a duplicate of it's address.
Name/Title of feed would be more informative.
![image](https://github.com/muffinista/rust-rss-to-fedi/assets/120734574/5b44035a-5cbd-468b-b076-9c05c2330470)
![image](https://github.com/muffinista/rust-rss-to-fedi/assets/120734574/ee2dfe52-45dd-446d-9db6-3d4cb5b8f11a)

**Comment by muffinista** [comment]
Good idea! I'm deploying this change shortly.
