### ISSUE TITLE
Edited description not seen in Fediverse profile view

### ISSUE THREAD

**Issue by joosep-georg** [muffinista/rust-rss-to-fedi#34]
![image](https://github.com/muffinista/rust-rss-to-fedi/assets/120734574/97648d45-2d59-423c-89b4-c84b1f8be955)
![image](https://github.com/muffinista/rust-rss-to-fedi/assets/120734574/c4c0e758-7a21-4d6e-92bb-b4aff98e7fd1)

**Comment by muffinista** [comment]
@joosep-georg I thought I'd replied to this but I guess not, sorry about that. Most instances cache this data for some period of time. Mastodon actually has a button in the user admin interface to pull fresh data. Anyway, I think that's what is probably happening here as I see the updated information when I check on my instance.

**Comment by joosep-georg** [comment]
Can confirm, descriptions have propagated by now.
