### ISSUE TITLE
Request: Display feed Name/Title in feedsin.space Home/Your feeds view

### ISSUE THREAD

**Issue by joosep-georg** [muffinista/rust-rss-to-fedi#40]
... in addition to Fediverse name/address.

For example:
![image](https://github.com/muffinista/rust-rss-to-fedi/assets/120734574/90a806c3-6b7e-44d6-a79a-4c92014d3678)

**Comment by muffinista** [comment]
Should look a little better now @joosep-georg

**Comment by joosep-georg** [comment]
It does indeed! Thank You!
**@fediversename** in bold is also very useful!
