### ISSUE TITLE
Weather.gov RSS Feeds not working

### ISSUE THREAD

**Issue by jjschwarz** [muffinista/rust-rss-to-fedi#41]
I am trying to create a new feed from Weather.gov for the RAH site with the URL:
https://www.weather.gov/rss_page.php?site_name=rah
which you can see from 
https://www.weather.gov/rah/ 
is the RSS feed.  It works fine in my feed reader, but the Feedsin.space site says:
Sorry, we couldn't find a valid feed at that URL

I can not seem to see any issue and I am able to retrieve the RSS data with wget as well.  Suggestions?

**Comment by muffinista** [comment]
Discussed elsewhere but I think this is fixed now.
