### ISSUE TITLE
Unable to load my feed

### ISSUE THREAD

**Issue by PJB3005** [muffinista/rust-rss-to-fedi#51]
Hi, I tried to set up [this RSS feed I made](https://central.spacestation14.io/changelog.xml). However the site just always gives me:

> Sorry, we couldn't find a valid feed at that URL

I cloned the repo to see if I could figure out what the problem is, but the feed seems to parse just fine if I run it through the tests.

**Comment by muffinista** [comment]
Hi @PJB3005 I think it might be an intermittent networking issue of some sort on the server itself, sometimes it'll work if you just try again.

**Comment by PJB3005** [comment]
Weird. It works now. Sorry for bothering then.
