### ISSUE TITLE
Couldn't find a valid feed at that URL although while w3-validator says ok

### ISSUE THREAD

**Issue by edlerluca** [muffinista/rust-rss-to-fedi#58]
Hi everyone,

I tried to add a new feed but get the error "Sorry, we couldn't find a valid feed at that URL".

RSS-Feed I want to add:
https://www.deutschlandfunk.de/lebenszeit-100.rss

Checked with:
https://validator.w3.org/feed/check.cgi -> "This is a valid RSS feed."

Check-URL:
http://validator.w3.org/check.cgi?url=https%3A//www.deutschlandfunk.de/lebenszeit-100.rss

Any idea?
Best

**Comment by muffinista** [comment]
Sorry for the delay on this, I have a feeling it will work for you now @edlerluca

**Comment by edlerluca** [comment]
Great, the feed works now. Thank you for your support!
