### ISSUE TITLE
Feed(s) stopped refreshing?

### ISSUE THREAD

**Issue by joosep-georg** [muffinista/rust-rss-to-fedi#59]
https://feedsin.space/feed/err.ee

Feed URL: https://nonsense.ee/rss-err.php
Refreshed at: 2023-11-04T22:17:10.283194Z

**Comment by muffinista** [comment]
@joosep-georg The feed should be refreshing now. Every now and then the app is losing database connectivity and it causes this problem, but it's proving very hard to troubleshoot.
