### ISSUE TITLE
Feed doesn't seem to work

### ISSUE THREAD

**Issue by haayman** [muffinista/rust-rss-to-fedi#69]
Hi,

I've set up this feed @fietsersbond@feedsin.space, but it doesn't seem to do anything. It says there are 12 posts, but they don't actually show up in my timeline? I can only see the one private message that was sent on creation.
Can you tell what's going wrong here?

![image](https://github.com/muffinista/rust-rss-to-fedi/assets/683823/2ee883b3-30cd-411f-b731-fb3eafa7f8c1)

**Comment by muffinista** [comment]
@haayman feedsin.space will only federate out new items in the feed, so once something is published in the RSS you should see it. I know the behavior is a little weird and I need to work on explaining how the site handles existing entries.

**Comment by haayman-imagem** [comment]
when I created the account there was a list of 10. Now there are 12

**Comment by muffinista** [comment]
OK. The logs say it federated properly but it's hard to prove. I'm following the account now to see what happens when it posts again.

**Comment by muffinista** [comment]
@haayman-imagem did you happen to get a post today?

**Comment by haayman-imagem** [comment]
I don't see it in my feed. It does appear on this page https://feedsin.space/feed/Fietsersbond but when I search for this account from my regular account I don't see anything, just the DM with my login link

**Comment by muffinista** [comment]
@haayman what's your fediverse account?

**Comment by haayman** [comment]
@haayman@todon.nl

**Comment by muffinista** [comment]
OK unless I'm mistaken you weren't actually following the account until today?

**Comment by haayman** [comment]
I refollowed in the hope this would trigger something.
I can see there are supposedly 13 posts, but i don't see them

**Comment by haayman** [comment]
It's just this account, the others work flawlessly

**Comment by muffinista** [comment]
OK, thanks. This is a weird one! I just messed around in the db a bit and manually delivered to most recent item, can you let me know if you got it?

**Comment by haayman-imagem** [comment]
yes I got the latest post.

**Comment by haayman** [comment]
I just got a post again. It seems to be solved
