### ISSUE TITLE
Allow users to delete feed accounts that are not in use

### ISSUE THREAD

**Issue by coolcat3467** [muffinista/rust-rss-to-fedi#78]
Currently, users cannot delete feed accounts that are no longer in use. Allowing users to delete inactive feed accounts will empower them to manage their accounts more effectively and contribute to system cleanliness.

__My Ideas__

User Interface Enhancement: Add a feature in the user interface that allows users to delete inactive feed accounts.

Confirmation Prompt: Implement a confirmation prompt to ensure users are aware of the consequences of deleting an account.

**Comment by muffinista** [comment]
@coolcat3467 do you mean being able to delete a feed account that you created? If you're logged in, there's a 'delete feed button' at the bottom of the feed details page.

**Comment by coolcat3467** [comment]
if I delete the feed does it delete the Mastodon account too?

**Comment by coolcat3467** [comment]
Figure out thx
